#!/bin/bash

# Users' Guide translation. Step 5
# Generate all mo files for Users' Guide
#
# This script MUST BE RUN from scripts/i18n/ folder, in source tree.
# As a result, all mo files are generated under source/locale directory
# the folders structure in source code.

# usage: ./users-guide-5
#------------------------------------------------------------------------------

E_SUCCESS=0         # success
E_NOARGS=65         # no arguments

echo "Generating all mo files for Users' Guide"
cd ../../docs/en/help/source
sphinx-intl build

echo "done"
exit $E_SUCCESS

