_("Configuration: Intervals - identification by ear");
_("Intervals");
_("Intervals to practise");
_("Unison");
_("minor 2nd");
_("Major 2nd");
_("minor 3rd");
_("Major 3rd");
_("Perfect 4th");
_("augm.4th / dim. 5th");
_("perfect 5th");
_("minor 6th");
_("Major 6th");
_("minor 7th");
_("Major 7th");
_("perfect 8th");
_("minor 9th");
_("Major 9th");
_("minor 10th");
_("Major 10th");
_("perfect 11th");
_("augm. 11th / dim. 12th");
_("perfect 12th");
_("minor 13th");
_("Major 13th");
_("minor 14th");
_("Major 14th");
_("Two octaves");
_("You must choose one at least! ");
_("Accidentals");
_("Accidentals");
_("&Use only notes from key signature");
_("&Allow chromatic accidentals");
_("Key signatures");
_("C Major / A minor");
_("G Major / E minor");
_("D Major / B minor");
_("A Major / F# minor");
_("E Major / C# minor");
_("B Major / G# minor");
_("F# Major / D# minor");
_("C# Major / A# minor");
_("Cb Major / Ab minor");
_("Gb Major / Eb minor");
_("D Major / B minor");
_("Ab Major / F minor");
_("Eb Major / C minor");
_("Bb Major / G minor");
_("F Major / D minor");
_("You must choose one key signature at least! ");
_("Other settings");
_("Notes' range");
_("Min. note");
_("Max. note");
_("Minimum pitch must be lower than maximum pitch ");
_("Intervals' types");
_("Harmonic (simultaneous notes)");
_("Melodic (ascending)");
_("Melodic (descending)");
_("You must choose one at least! ");
_("Start both intervals with the same note");
_("Accept");
_("Cancel");
_("It is not possible to generate any interval. Selected notes range interval (see tab 'Other settings') is lower than minimun allowed interval (see tab 'Intervals')");
//DlgCfgScoreReading.xrc 
_("Score generation settings");
_("Clefs and Notes");
_("Mark the clefts to use and set up the minimun and\nmaximum pitches for the notes to use with each selected clef.");
_("G clef (violin)");
_("Min. note");
_("Max. note");
_("F clef on 4th line (bass)");
_("Min. note");
_("Max. note");
_("F clef on 3rd line");
_("Min. note");
_("Max. note");
_("C clef on 1st line (soprano)");
_("Min. note");
_("Max. note");
_("C clef on 2nd line (mezzo soprano)");
_("Min. note");
_("Max. note");
_("C clef on 3rd line (contralto)");
_("Min. note");
_("Max. note");
_("C clef on 4th line (tenor)");
_("Min. note");
_("Max. note");
_("You must choose at least one clef! ");
_("Minimum pitch must be lower than maximum pitch ");
_("Maximum interval between two consecutive notes");
_("Time signatures");
_("Binary subdivision");
_("2 4 time signature");
_("3 4");
_("4 4");
_("2 8");
_("2 2");
_("3 2");
_("Ternary subdivision");
_("6 8 time signature");
_("9 8");
_("12 8");
_("3 8");
_("You must choose at least one time signature! ");
_("Key signatures");
_("C Major / A minor");
_("G Major / E minor");
_("D Major / B minor");
_("A Major / F# minor");
_("E Major / C# minor");
_("B Major / G# minor");
_("F# Major / D# minor");
_("C# Major / A# minor");
_("Cb Major / Ab minor");
_("Gb Major / Eb minor");
_("D Major / B minor");
_("Ab Major / F minor");
_("Eb Major / C minor");
_("Bb Major / G minor");
_("F Major / D minor");
_("You must choose at least one key signature! ");
_("Rhymths");
_("Add rhythm");
_("Delete rhythm");
_("Accept");
_("&Cancel");
//DlgPatternEditor.xrc 
_("Pattern's editor");
_("Step 1. Choose attributes for next note/rest to enter:");
_("Dotted");
_("Tied next");
_("Not beamed");
_("Start of a beamed group");
_("Continue in beamed group");
_("End of beamed group");
_("Step 2. Enter the the desired note/rest:");
_("Whole note");
_("Half note");
_("Quarter note");
_("8th note");
_("16th note");
_("32th note");
_("64th note");
_("Whole rest");
_("Half rest");
_("Quarter rest");
_("8th rest");
_("16th rest");
_("32th rest");
_("64th rest");
_("Barline");
_("Clear all");
_("Undo");
_("Redo");
_("Accept");
_("Cancel");
//LangOptionsPanel.xrc 
_("Language preferences");
_("Choose language to use:");
//ToolbarsOptPanel.xrc 
_("Preferences for toolbars");
_("Icons' size");
_("&Small");
_("&Medium");
_("&Large");
_("Labels");
_("&No labels");
_("Labels &bottom");
_("Labels &right");
//InternetOptPanel.xrc 
_("Internet connection options");
_("Software updates");
_("Check for updates");
_("Last successful check:");
_("dd/mm/aaaa");
_("Use a proxy server to connect to Internet");
_("Proxy settings");
_("Server settings");
_("Host:");
_("Port number:");
_("Please enter data for both, host name and port number");
_("Proxy server requires authentication");
_("Authentication");
_("Username:");
_("Password:");
_("Please enter data for both, user name and password");
//UpdaterDlgInfo.xrc 
_("LenMus Phonascus updater");
_("Available updates");
_("Item description");
_("Download selected items");
_("&Cancel");
//UpdaterDlgStart.xrc 
_("LenMus Phonascus updater");
_("Checking for available updates");
_("This program will connect to LenMus website and look for \navailable updates.\n\nPress 'Proceed' to start.");
_("Proceed");
_("&Cancel");
//DlgCfgIdfyChord.xrc 
_("Configuration: Chords' identification");
_("Chords");
_("Triads");
_("Major triad");
_("Minor triad");
_("Augmented triad");
_("Diminished triad");
_("Suspended (4th)");
_("Suspended (2nd)");
_("Sevenths");
_("Major 7th");
_("Minor 7th");
_("Augmented 7th");
_("Diminished 7th");
_("Dominant 7th");
_("Half diminished 7th");
_("Augmented major 7th");
_("Minor major 7th");
_("Other chords");
_("Major 6th");
_("Augmented 6th");
_("Minor 6th");
_("You must choose one at least! ");
_("Key signatures");
_("Key signatures");
_("C Major / A minor");
_("G Major / E minor");
_("D Major / B minor");
_("A Major / F# minor");
_("E Major / C# minor");
_("B Major / G# minor");
_("F# Major / D# minor");
_("C# Major / A# minor");
_("Cb Major / Ab minor");
_("Gb Major / Eb minor");
_("D Major / B minor");
_("Ab Major / F minor");
_("Eb Major / C minor");
_("Bb Major / G minor");
_("F Major / D minor");
_("You must choose one key signature at least! ");
_("Other settings");
_("Play modes");
_("Chord (simultaneous notes)");
_("Arpegiated (ascending)");
_("Arpegiated (descending)");
_("You must choose one at least! ");
_("Allow inversions");
_("Display key signature");
_("Accept");
_("Cancel");
//DlgCfgIdfyScale.xrc 
_("Configuration: Scales' identification");
_("Scales");
_("Major scales");
_("Natural");
_("Type II");
_("Type III");
_("Type IV");
_("Minor scales");
_("Natural");
_("Dorian");
_("Harmonic");
_("Melodic");
_("Gregorian scales");
_("Ionian");
_("Mixolydian");
_("Dorian");
_("Aeolian");
_("Phrygian");
_("Locrian");
_("Lydian");
_("Other scales");
_("Pentatonic major");
_("Pentatonic minor");
_("Whole tones");
_("Blues");
_("Chromatic");
_("You must choose one at least! ");
_("Key signatures");
_("Key signatures");
_("C Major / A minor");
_("G Major / E minor");
_("D Major / B minor");
_("A Major / F# minor");
_("E Major / C# minor");
_("B Major / G# minor");
_("F# Major / D# minor");
_("C# Major / A# minor");
_("Cb Major / Ab minor");
_("Gb Major / Eb minor");
_("Db Major / Bb minor");
_("Ab Major / F minor");
_("Eb Major / C minor");
_("Bb Major / G minor");
_("F Major / D minor");
_("You must choose one key signature at least! ");
_("Other settings");
_("Play mode");
_("&Ascending");
_("&Descending");
_("&Both");
_("Display key signature");
_("Accept");
_("Cancel");
//DlgCfgIdfyCadence.xrc 
_("Cadence settings");
_("Cadences");
_("Terminal");
_("Perfect authentic");
_("V --> I");
_("V7 --> I");
_("V aug5 --> I");
_("V dim5 --> I");
_("check/uncheck all");
_("Imperfect authentic");
_("V --> I (one or both with inversions)");
_("Plagal");
_("IV --> I");
_("IVm --> I");
_("II/6 --> I");
_("IIm/6 --> I");
_("check/uncheck all");
_("Transient");
_("Half cadences");
_("IIm/6 --> V");
_("IV --> V");
_("I --> V");
_("I/64 --> V");
_("IVm/6 --> V (Phrygian half cadence)");
_("II --> V");
_("Neapolitan sixth --> V");
_("VI+ --> V");
_("check/uncheck all");
_("Deceptive");
_("V --> IV");
_("V --> IVm");
_("V --> IIm");
_("V --> III");
_("V --> VII");
_("V --> VI");
_("V --> VIm");
_("check/uncheck all");
_("Key signatures");
_("Key signatures");
_("C Major");
_("G Major");
_("D Major");
_("A Major");
_("E Major");
_("B Major");
_("F# Major");
_("C# Major");
_("Cb Major");
_("Gb Major");
_("Db Major");
_("Ab Major");
_("Eb Major");
_("Bb Major");
_("F Major");
_("A minor");
_("E minor");
_("B minor");
_("F# minor");
_("C# minor");
_("G# minor");
_("D# minor");
_("A# minor");
_("Ab minor");
_("Eb minor");
_("Bb minor");
_("F minor");
_("C minor");
_("G minor");
_("D minor");
_("check/uncheck all major");
_("check/uncheck all minor");
_("You must choose at least one key signature! ");
_("How to show key signature?");
_("&Play A4 note");
_("Play &tonic chord");
_("Answer buttons");
_("Type of desired answer");
_("Identify cadence &group (terminal/transient)");
_("Identify cadence &type");
_("Cadence types");
_("Terminal cadences");
_("Perfect authentic");
_("Imperfect authentic");
_("Plagal");
_("Transient cadences");
_("Deceptive");
_("Half cadence");
_("You must choose al least two buttons! ");
_("You must choose at least one cadence in tab 'cadences'! ");
_("Accept");
_("Cancel");
